language: node_js

node_js:
  - '14'

before_install:
  - uname --all

install:
  - yarn install

script:
  - yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  keep_history: true
  local_dir: build
  on:
    branch: master
