language: node_js

node_js:
  - "12"

before_install:
  - uname --all

install:
  - yarn install

script:
  - CI=false yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  keep_history: true
  on:
    branch: master
