name: Main
on:
  push:
    branches: [master]
jobs:
  All:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Deploy
        run: |
          git config --global user.name $user_name
          git config --global user.email $user_email
          git remote set-url origin https://${gh_pages_deploy_token}@github.com/${repo}
          yarn
          yarn deploy
        env:
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          repo: ${{github.repository}}
          gh_pages_deploy_token: ${{ secrets.GH_PAGES_DEPLOY }}



